name: meteo
description: Une application de météo basée sur la localisation
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  auto_route: ^6.4.0
  flex_color_scheme: ^7.0.4
  flutter:
    sdk: flutter
  flutter_mapbox_autocomplete: ^2.0.0
  geolocator: ^9.0.2
  http: ^0.13.5
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true